import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

// CAP score data for 03/10/2025 - complete dataset
const AGENT_DATA = [
  {
    tenure: 8.4,
    status: "P",
    site: "AUS",
    manager: "David Druxman",
    rank: 1,
    name: "Iesha Alexander",
    capScore: 237,
    closeRate: 26.6,
    avgPremium: 1385,
    placeRate: 64.4,
    leadsPerDay: 7.9,
  },
  {
    tenure: 8.4,
    status: "P",
    site: "AUS",
    manager: "David Druxman",
    rank: 2,
    name: "Jremekyo Anderson",
    capScore: 236,
    closeRate: 26.3,
    avgPremium: 1180,
    placeRate: 75.9,
    leadsPerDay: 5.7,
  },
  {
    tenure: 9.5,
    status: "P",
    site: "CHA",
    manager: "Nisrin Hajmahmoud",
    rank: 3,
    name: "Jimmie Royster",
    capScore: 219,
    closeRate: 32.4,
    avgPremium: 952,
    placeRate: 70.9,
    leadsPerDay: 7.4,
  },
  {
    tenure: 9.5,
    status: "P",
    site: "CHA",
    manager: "Katelyn Helms",
    rank: 4,
    name: "Asaad Weaver",
    capScore: 216,
    closeRate: 18.3,
    avgPremium: 1576,
    placeRate: 75.0,
    leadsPerDay: 7.1,
  },
  {
    tenure: 12.6,
    status: "P",
    site: "CHA",
    manager: "Jovan Espinoza",
    rank: 5,
    name: "Robert Carter",
    capScore: 216,
    closeRate: 21.0,
    avgPremium: 1425,
    placeRate: 72.2,
    leadsPerDay: 6.2,
  },
  {
    tenure: 7.2,
    status: "P",
    site: "CHA",
    manager: "Jacob Fuller",
    rank: 6,
    name: "Miguel Roman",
    capScore: 216,
    closeRate: 30.0,
    avgPremium: 1144,
    placeRate: 62.8,
    leadsPerDay: 8.0,
  },
  {
    tenure: 3.7,
    status: "P",
    site: "CHA",
    manager: "Jamal Gipson",
    rank: 7,
    name: "Loren Johnson",
    capScore: 205,
    closeRate: 20.3,
    avgPremium: 1450,
    placeRate: 69.5,
    leadsPerDay: 7.9,
  },
  {
    tenure: 12.6,
    status: "P",
    site: "CHA",
    manager: "Nisrin Hajmahmoud",
    rank: 8,
    name: "Serena Cowan",
    capScore: 203,
    closeRate: 29.7,
    avgPremium: 1269,
    placeRate: 53.8,
    leadsPerDay: 6.4,
  },
  {
    tenure: 9.5,
    status: "P",
    site: "AUS",
    manager: "Mario Herrera",
    rank: 9,
    name: "Roza Veravillalba",
    capScore: 194,
    closeRate: 17.4,
    avgPremium: 2004,
    placeRate: 55.6,
    leadsPerDay: 6.9,
  },
  {
    tenure: 9.5,
    status: "P",
    site: "AUS",
    manager: "Mario Herrera",
    rank: 10,
    name: "Diana Roe",
    capScore: 186,
    closeRate: 16.9,
    avgPremium: 1410,
    placeRate: 78.0,
    leadsPerDay: 7.1,
  },
  {
    tenure: 4.9,
    status: "P",
    site: "AUS",
    manager: "Patricia Lewis",
    rank: 11,
    name: "Jonathon Mejia",
    capScore: 185,
    closeRate: 22.9,
    avgPremium: 1503,
    placeRate: 53.8,
    leadsPerDay: 8.3,
  },
  {
    tenure: 5.3,
    status: "P",
    site: "CHA",
    manager: "Jovan Espinoza",
    rank: 12,
    name: "Kenny Mclaughlin",
    capScore: 185,
    closeRate: 25.9,
    avgPremium: 1224,
    placeRate: 58.3,
    leadsPerDay: 5.4,
  },
  {
    tenure: 5.8,
    status: "P",
    site: "CHA",
    manager: "Katelyn Helms",
    rank: 13,
    name: "Keviantae Paul",
    capScore: 179,
    closeRate: 23.7,
    avgPremium: 1132,
    placeRate: 66.7,
    leadsPerDay: 5.9,
  },
  {
    tenure: 10.7,
    status: "P",
    site: "CHA",
    manager: "Jovan Espinoza",
    rank: 14,
    name: "Peter Nguyen",
    capScore: 176,
    closeRate: 23.0,
    avgPremium: 1359,
    placeRate: 56.4,
    leadsPerDay: 7.4,
  },
  {
    tenure: 16.5,
    status: "P",
    site: "CHA",
    manager: "Jovan Espinoza",
    rank: 15,
    name: "Hunter Case",
    capScore: 163,
    closeRate: 14.5,
    avgPremium: 1598,
    placeRate: 70.2,
    leadsPerDay: 6.2,
  },
  {
    tenure: 7.2,
    status: "P",
    site: "CHA",
    manager: "Vincent Blanchett",
    rank: 16,
    name: "DeAngela Harris",
    capScore: 153,
    closeRate: 19.8,
    avgPremium: 1127,
    placeRate: 68.4,
    leadsPerDay: 8.1,
  },
  {
    tenure: 9.5,
    status: "P",
    site: "AUS",
    manager: "David Druxman",
    rank: 17,
    name: "Justin Hinze",
    capScore: 152,
    closeRate: 18.1,
    avgPremium: 1101,
    placeRate: 76.3,
    leadsPerDay: 7.2,
  },
  {
    tenure: 8.4,
    status: "P",
    site: "AUS",
    manager: "Frederick Holguin",
    rank: 18,
    name: "Eric Marrs",
    capScore: 147,
    closeRate: 17.6,
    avgPremium: 1278,
    placeRate: 65.3,
    leadsPerDay: 9.1,
  },
  {
    tenure: 9.5,
    status: "P",
    site: "AUS",
    manager: "Patricia Lewis",
    rank: 19,
    name: "Jovon Holts",
    capScore: 147,
    closeRate: 19.5,
    avgPremium: 1075,
    placeRate: 69.9,
    leadsPerDay: 7.7,
  },
  {
    tenure: 8.4,
    status: "P",
    site: "AUS",
    manager: "Lanae Edwards",
    rank: 20,
    name: "Duncan Ordenana",
    capScore: 146,
    closeRate: 12.5,
    avgPremium: 1588,
    placeRate: 73.4,
    leadsPerDay: 6.4,
  },
  {
    tenure: 8.4,
    status: "P",
    site: "CHA",
    manager: "Vincent Blanchett",
    rank: 21,
    name: "Douglas Yang",
    capScore: 145,
    closeRate: 19.7,
    avgPremium: 1273,
    placeRate: 57.7,
    leadsPerDay: 7.6,
  },
  {
    tenure: 4.4,
    status: "P",
    site: "AUS",
    manager: "Mario Herrera",
    rank: 22,
    name: "Michelle Brown",
    capScore: 139,
    closeRate: 16.2,
    avgPremium: 1119,
    placeRate: 76.6,
    leadsPerDay: 6.8,
  },
  {
    tenure: 4.4,
    status: "P",
    site: "CHA",
    manager: "Patricia Lewis",
    rank: 23,
    name: "Leif Carlson",
    capScore: 137,
    closeRate: 20.0,
    avgPremium: 1225,
    placeRate: 56.1,
    leadsPerDay: 7.0,
  },
  {
    tenure: 9.5,
    status: "P",
    site: "CHA",
    manager: "David Druxman",
    rank: 24,
    name: "Kierra Smith",
    capScore: 135,
    closeRate: 19.6,
    avgPremium: 1124,
    placeRate: 61.2,
    leadsPerDay: 9.7,
  },
  {
    tenure: 4.9,
    status: "P",
    site: "CHA",
    manager: "Jamal Gipson",
    rank: 25,
    name: "Alvin Fulmore",
    capScore: 134,
    closeRate: 17.6,
    avgPremium: 1284,
    placeRate: 59.4,
    leadsPerDay: 7.4,
  },
  {
    tenure: 4.9,
    status: "P",
    site: "CHA",
    manager: "Jacob Fuller",
    rank: 26,
    name: "Joe Coleman",
    capScore: 134,
    closeRate: 15.5,
    avgPremium: 1553,
    placeRate: 55.6,
    leadsPerDay: 7.1,
  },
  {
    tenure: 9.5,
    status: "P",
    site: "CHA",
    manager: "Katelyn Helms",
    rank: 27,
    name: "Kyle Williford",
    capScore: 131,
    closeRate: 21.9,
    avgPremium: 829,
    placeRate: 72.1,
    leadsPerDay: 6.4,
  },
  {
    tenure: 2.5,
    status: "P",
    site: "CHA",
    manager: "Jovan Espinoza",
    rank: 28,
    name: "Montrell Morgan",
    capScore: 130,
    closeRate: 18.7,
    avgPremium: 872,
    placeRate: 80.0,
    leadsPerDay: 7.5,
  },
  {
    tenure: 3.7,
    status: "P",
    site: "AUS",
    manager: "David Druxman",
    rank: 29,
    name: "Tim Dominguez",
    capScore: 126,
    closeRate: 16.9,
    avgPremium: 1240,
    placeRate: 60.0,
    leadsPerDay: 8.9,
  },
  {
    tenure: 9.5,
    status: "P",
    site: "AUS",
    manager: "Lanae Edwards",
    rank: 30,
    name: "Magifira Jemal",
    capScore: 122,
    closeRate: 22.1,
    avgPremium: 1106,
    placeRate: 50.0,
    leadsPerDay: 7.7,
  },
  {
    tenure: 5.8,
    status: "P",
    site: "CHA",
    manager: "Katelyn Helms",
    rank: 31,
    name: "Kb Bolar",
    capScore: 118,
    closeRate: 15.2,
    avgPremium: 1128,
    placeRate: 68.6,
    leadsPerDay: 6.6,
  },
  {
    tenure: 6.5,
    status: "P",
    site: "CHA",
    manager: "Nisrin Hajmahmoud",
    rank: 32,
    name: "Chris Chen",
    capScore: 117,
    closeRate: 19.0,
    avgPremium: 1088,
    placeRate: 56.8,
    leadsPerDay: 5.8,
  },
  {
    tenure: 6.5,
    status: "P",
    site: "CHA",
    manager: "Vincent Blanchett",
    rank: 33,
    name: "Adelina Guardado",
    capScore: 117,
    closeRate: 13.9,
    avgPremium: 1447,
    placeRate: 58.1,
    leadsPerDay: 7.9,
  },
  {
    tenure: 5.8,
    status: "P",
    site: "CHA",
    manager: "Jacob Fuller",
    rank: 34,
    name: "Quinn Mcleod",
    capScore: 117,
    closeRate: 24.6,
    avgPremium: 1117,
    placeRate: 42.4,
    leadsPerDay: 5.7,
  },
  {
    tenure: 4.9,
    status: "P",
    site: "AUS",
    manager: "David Druxman",
    rank: 35,
    name: "Alicia O'Bryant",
    capScore: 115,
    closeRate: 17.6,
    avgPremium: 1040,
    placeRate: 62.9,
    leadsPerDay: 6.8,
  },
  {
    tenure: 9.5,
    status: "P",
    site: "CHA",
    manager: "Katelyn Helms",
    rank: 36,
    name: "Arlethe Guevara",
    capScore: 114,
    closeRate: 18.7,
    avgPremium: 1092,
    placeRate: 55.6,
    leadsPerDay: 7.5,
  },
  {
    tenure: 5.3,
    status: "P",
    site: "AUS",
    manager: "Frederick Holguin",
    rank: 37,
    name: "Doug Curttright",
    capScore: 113,
    closeRate: 24.7,
    avgPremium: 931,
    placeRate: 49.1,
    leadsPerDay: 7.3,
  },
  {
    tenure: 13.5,
    status: "P",
    site: "CHA",
    manager: "Nisrin Hajmahmoud",
    rank: 38,
    name: "Dustin Gunter",
    capScore: 106,
    closeRate: 15.1,
    avgPremium: 1200,
    placeRate: 58.6,
    leadsPerDay: 7.3,
  },
  {
    tenure: 9.5,
    status: "P",
    site: "CHA",
    manager: "Vincent Blanchett",
    rank: 39,
    name: "Mitchell Pitman",
    capScore: 104,
    closeRate: 18.2,
    avgPremium: 1176,
    placeRate: 48.7,
    leadsPerDay: 7.7,
  },
  {
    tenure: 6.5,
    status: "P",
    site: "CHA",
    manager: "Nisrin Hajmahmoud",
    rank: 40,
    name: "Jahne Spears",
    capScore: 98,
    closeRate: 13.6,
    avgPremium: 949,
    placeRate: 75.8,
    leadsPerDay: 4.4,
  },
  {
    tenure: 7.2,
    status: "P",
    site: "AUS",
    manager: "Frederick Holguin",
    rank: 41,
    name: "John Sivy",
    capScore: 97,
    closeRate: 12.5,
    avgPremium: 1260,
    placeRate: 61.8,
    leadsPerDay: 8.8,
  },
  {
    tenure: 5.8,
    status: "P",
    site: "CHA",
    manager: "Katelyn Helms",
    rank: 42,
    name: "Lexi Salinas",
    capScore: 96,
    closeRate: 15.2,
    avgPremium: 1040,
    placeRate: 60.6,
    leadsPerDay: 6.6,
  },
  {
    tenure: 13.5,
    status: "P",
    site: "CHA",
    manager: "Vincent Blanchett",
    rank: 43,
    name: "Lynethe Guevara",
    capScore: 95,
    closeRate: 23.5,
    avgPremium: 662,
    placeRate: 61.2,
    leadsPerDay: 5.1,
  },
  {
    tenure: 21.4,
    status: "P",
    site: "CHA",
    manager: "Nisrin Hajmahmoud",
    rank: 44,
    name: "Camryn Anderson",
    capScore: 94,
    closeRate: 15.5,
    avgPremium: 1268,
    placeRate: 47.8,
    leadsPerDay: 7.1,
  },
  {
    tenure: 4.9,
    status: "P",
    site: "AUS",
    manager: "David Druxman",
    rank: 45,
    name: "Billy Slater",
    capScore: 93,
    closeRate: 14.0,
    avgPremium: 1055,
    placeRate: 63.3,
    leadsPerDay: 4.3,
  },
  {
    tenure: 15.6,
    status: "P",
    site: "CHA",
    manager: "Jamal Gipson",
    rank: 46,
    name: "DaVon Loney",
    capScore: 93,
    closeRate: 10.9,
    avgPremium: 1392,
    placeRate: 61.4,
    leadsPerDay: 6.4,
  },
  {
    tenure: 3.7,
    status: "P",
    site: "AUS",
    manager: "Patricia Lewis",
    rank: 47,
    name: "Brandon Escort",
    capScore: 91,
    closeRate: 15.5,
    avgPremium: 1128,
    placeRate: 52.2,
    leadsPerDay: 8.4,
  },
  {
    tenure: 7.2,
    status: "P",
    site: "AUS",
    manager: "Lanae Edwards",
    rank: 48,
    name: "Jack Benken",
    capScore: 90,
    closeRate: 11.8,
    avgPremium: 1339,
    placeRate: 57.1,
    leadsPerDay: 7.6,
  },
  {
    tenure: 5.8,
    status: "P",
    site: "CHA",
    manager: "Vincent Blanchett",
    rank: 49,
    name: "Gee Grayer",
    capScore: 88,
    closeRate: 16.2,
    avgPremium: 1114,
    placeRate: 49.0,
    leadsPerDay: 6.8,
  },
  {
    tenure: 6.5,
    status: "P",
    site: "CHA",
    manager: "Vincent Blanchett",
    rank: 50,
    name: "Gabrielle Smith",
    capScore: 88,
    closeRate: 13.9,
    avgPremium: 1010,
    placeRate: 62.9,
    leadsPerDay: 7.9,
  },
  {
    tenure: 6.5,
    status: "P",
    site: "CHA",
    manager: "Jovan Espinoza",
    rank: 51,
    name: "Kenya Caldwell",
    capScore: 85,
    closeRate: 12.7,
    avgPremium: 1008,
    placeRate: 66.7,
    leadsPerDay: 7.1,
  },
  {
    tenure: 9.5,
    status: "P",
    site: "CHA",
    manager: "Katelyn Helms",
    rank: 52,
    name: "Beau Carson",
    capScore: 85,
    closeRate: 11.3,
    avgPremium: 1199,
    placeRate: 62.5,
    leadsPerDay: 7.1,
  },
  {
    tenure: 22.6,
    status: "P",
    site: "CHA",
    manager: "Katelyn Helms",
    rank: 53,
    name: "Tyler Jacobson",
    capScore: 85,
    closeRate: 8.3,
    avgPremium: 1435,
    placeRate: 71.0,
    leadsPerDay: 2.4,
  },
  {
    tenure: 6.5,
    status: "P",
    site: "CHA",
    manager: "Jovan Espinoza",
    rank: 54,
    name: "Damond Outing",
    capScore: 81,
    closeRate: 17.4,
    avgPremium: 991,
    placeRate: 46.7,
    leadsPerDay: 4.6,
  },
  {
    tenure: 6.5,
    status: "P",
    site: "AUS",
    manager: "Lanae Edwards",
    rank: 55,
    name: "Rachel Choate",
    capScore: 78,
    closeRate: 16.1,
    avgPremium: 985,
    placeRate: 49.1,
    leadsPerDay: 5.6,
  },
  {
    tenure: 4.9,
    status: "P",
    site: "AUS",
    manager: "Frederick Holguin",
    rank: 56,
    name: "Ron Rydzfski",
    capScore: 77,
    closeRate: 12.0,
    avgPremium: 1031,
    placeRate: 62.4,
    leadsPerDay: 7.5,
  },
  {
    tenure: 3.7,
    status: "P",
    site: "AUS",
    manager: "Lanae Edwards",
    rank: 57,
    name: "Jeff Korioth",
    capScore: 75,
    closeRate: 15.1,
    avgPremium: 663,
    placeRate: 75.0,
    leadsPerDay: 7.3,
  },
  {
    tenure: 3.7,
    status: "P",
    site: "CHA",
    manager: "Jamal Gipson",
    rank: 58,
    name: "Damien King",
    capScore: 75,
    closeRate: 15.0,
    avgPremium: 907,
    placeRate: 55.0,
    leadsPerDay: 8,
  },
  {
    tenure: 5.3,
    status: "P",
    site: "AUS",
    manager: "Frederick Holguin",
    rank: 59,
    name: "Micah Black",
    capScore: 75,
    closeRate: 10.5,
    avgPremium: 1233,
    placeRate: 57.6,
    leadsPerDay: 3.8,
  },
  {
    tenure: 5.3,
    status: "P",
    site: "AUS",
    manager: "Frederick Holguin",
    rank: 60,
    name: "Austin Houser",
    capScore: 73,
    closeRate: 15.4,
    avgPremium: 772,
    placeRate: 61.4,
    leadsPerDay: 1.3,
  },
  {
    tenure: 7.2,
    status: "P",
    site: "AUS",
    manager: "Mario Herrera",
    rank: 61,
    name: "Mark Garcia",
    capScore: 73,
    closeRate: 12.1,
    avgPremium: 1142,
    placeRate: 52.6,
    leadsPerDay: 5.8,
  },
  {
    tenure: 3.7,
    status: "P",
    site: "CHA",
    manager: "Jacob Fuller",
    rank: 62,
    name: "Dennis Smith",
    capScore: 68,
    closeRate: 16.0,
    avgPremium: 1273,
    placeRate: 33.3,
    leadsPerDay: 7.5,
  },
  {
    tenure: 5.8,
    status: "P",
    site: "AUS",
    manager: "Mario Herrera",
    rank: 63,
    name: "Jaime Valdez",
    capScore: 65,
    closeRate: 8.6,
    avgPremium: 1304,
    placeRate: 57.7,
    leadsPerDay: 7,
  },
  {
    tenure: 5.8,
    status: "P",
    site: "CHA",
    manager: "Nisrin Hajmahmoud",
    rank: 64,
    name: "Niko Smallwood",
    capScore: 59,
    closeRate: 8.8,
    avgPremium: 1068,
    placeRate: 62.8,
    leadsPerDay: 8,
  },
  {
    tenure: 8.4,
    status: "P",
    site: "AUS",
    manager: "Lanae Edwards",
    rank: 65,
    name: "Amy Slusarski",
    capScore: 55,
    closeRate: 11.6,
    avgPremium: 826,
    placeRate: 57.3,
    leadsPerDay: 4.3,
  },
  {
    tenure: 3.2,
    status: "P",
    site: "CHA",
    manager: "Jamal Gipson",
    rank: 66,
    name: "Kevin Gray",
    capScore: 53,
    closeRate: 6.1,
    avgPremium: 1848,
    placeRate: 46.7,
    leadsPerDay: 8.2,
  },
  {
    tenure: 3.7,
    status: "P",
    site: "AUS",
    manager: "Frederick Holguin",
    rank: 67,
    name: "Andy Nickleson",
    capScore: 51,
    closeRate: 8.2,
    avgPremium: 954,
    placeRate: 64.6,
    leadsPerDay: 8.5,
  },
  {
    tenure: 8.4,
    status: "P",
    site: "CHA",
    manager: "Jamal Gipson",
    rank: 68,
    name: "Johnathan Hubbard",
    capScore: 48,
    closeRate: 5.7,
    avgPremium: 1112,
    placeRate: 75.0,
    leadsPerDay: 7,
  },
  {
    tenure: 2.1,
    status: "T",
    site: "CHA",
    manager: "Jamal Gipson",
    rank: "T1",
    name: "Alexis Alexander",
    capScore: 113,
    closeRate: 7.6,
    avgPremium: 1489,
    placeRate: 100.0,
    leadsPerDay: 6.6,
  },
  {
    tenure: 2.5,
    status: "T",
    site: "AUS",
    manager: "Frederick Holguin",
    rank: "T2",
    name: "Nikia Lewis",
    capScore: 107,
    closeRate: 14.7,
    avgPremium: 1090,
    placeRate: 66.7,
    leadsPerDay: 10.2,
  },
  {
    tenure: 3.7,
    status: "T",
    site: "AUS",
    manager: "Mario Herrera",
    rank: "T3",
    name: "Dawn Dawson",
    capScore: 83,
    closeRate: 11.1,
    avgPremium: 1096,
    placeRate: 67.9,
    leadsPerDay: 6.3,
  },
  {
    tenure: 2.5,
    status: "T",
    site: "CHA",
    manager: "Jacob Fuller",
    rank: "T4",
    name: "Jeffrey Rosenberg",
    capScore: 50,
    closeRate: 11.1,
    avgPremium: 823,
    placeRate: 55.0,
    leadsPerDay: 7.2,
  },
  {
    tenure: 2.5,
    status: "T",
    site: "CHA",
    manager: "Jacob Fuller",
    rank: "T5",
    name: "Wenny Gooding",
    capScore: 47,
    closeRate: 7.5,
    avgPremium: 934,
    placeRate: 66.7,
    leadsPerDay: 5.3,
  },
  {
    tenure: 2.5,
    status: "T",
    site: "CHA",
    manager: "Jamal Gipson",
    rank: "T6",
    name: "Dawn Strong",
    capScore: 26,
    closeRate: 6.0,
    avgPremium: 870,
    placeRate: 50.0,
    leadsPerDay: 8.3,
  },
  {
    tenure: 1.6,
    status: "T",
    site: "AUS",
    manager: "Patricia Lewis",
    rank: null,
    name: "Celeste Garcia",
    capScore: 0,
    closeRate: 15.6,
    avgPremium: 882,
    placeRate: 0,
    leadsPerDay: 7.7,
  },
  {
    tenure: 1.6,
    status: "T",
    site: "AUS",
    manager: "Mario Herrera",
    rank: null,
    name: "Crystal Kurtanic",
    capScore: 0,
    closeRate: 13.4,
    avgPremium: 1268,
    placeRate: 0,
    leadsPerDay: 8.2,
  },
  {
    tenure: 1.6,
    status: "T",
    site: "AUS",
    manager: "Patricia Lewis",
    rank: null,
    name: "Cynthia Mbaka",
    capScore: 0,
    closeRate: 14.7,
    avgPremium: 1072,
    placeRate: 0,
    leadsPerDay: 6.8,
  },
  {
    tenure: 1.6,
    status: "T",
    site: "AUS",
    manager: "Patricia Lewis",
    rank: null,
    name: "Katherine Freeman",
    capScore: 0,
    closeRate: 7.4,
    avgPremium: 819,
    placeRate: 0,
    leadsPerDay: 6.8,
  },
  {
    tenure: 1.1,
    status: "T",
    site: "AUS",
    manager: "Lanae Edwards",
    rank: null,
    name: "Pedro Rodrigues",
    capScore: 0,
    closeRate: 10.5,
    avgPremium: 1105,
    placeRate: 0,
    leadsPerDay: 7.6,
  },
  {
    tenure: 1.6,
    status: "T",
    site: "AUS",
    manager: "Lanae Edwards",
    rank: null,
    name: "Rose Scales",
    capScore: 0,
    closeRate: 7.5,
    avgPremium: 776,
    placeRate: 0,
    leadsPerDay: 8,
  },
  {
    tenure: 1.6,
    status: "T",
    site: "CHA",
    manager: "Brent Lahti",
    rank: null,
    name: "Chris Williams",
    capScore: 0,
    closeRate: 13.3,
    avgPremium: 1170,
    placeRate: 0,
    leadsPerDay: 6,
  },
  {
    tenure: 1.6,
    status: "T",
    site: "CHA",
    manager: "Katelyn Helms",
    rank: null,
    name: "Don Mccoy",
    capScore: 0,
    closeRate: 18.4,
    avgPremium: 957,
    placeRate: 0,
    leadsPerDay: 9.8,
  },
  {
    tenure: 1.1,
    status: "T",
    site: "CHA",
    manager: "Brent Lahti",
    rank: null,
    name: "Gerard Apadula",
    capScore: 0,
    closeRate: 23.8,
    avgPremium: 755,
    placeRate: 0,
    leadsPerDay: 4.2,
  },
  {
    tenure: 1.1,
    status: "T",
    site: "CHA",
    manager: "Jovan Espinoza",
    rank: null,
    name: "Quincy Jones",
    capScore: 0,
    closeRate: 5.3,
    avgPremium: 2075,
    placeRate: 0,
    leadsPerDay: 7.6,
  },
];

// Function to find or create a team
async function findOrCreateTeam(managerName, site) {
  // Look up team by manager name
  let team = await prisma.team.findFirst({
    where: {
      name: managerName,
    },
  });

  // Create the team if it doesn't exist
  if (!team) {
    team = await prisma.team.create({
      data: {
        name: managerName,
        description: `${site} Team`,
      },
    });
    console.log(`Created team for ${managerName} in ${site}`);
  }

  return team;
}

// Process an agent and add to database
async function processAgent(agentData) {
  try {
    // Find or create the team
    const team = await findOrCreateTeam(agentData.manager, agentData.site);

    // Parse the agent's name
    const nameParts = agentData.name.split(" ");
    const firstName = nameParts[0];
    const lastName = nameParts.slice(1).join(" ");

    // Generate a unique email with timestamp
    const timestamp = Date.now() + Math.floor(Math.random() * 1000);
    const email = `${firstName.toLowerCase()}.${lastName
      .toLowerCase()
      .replace(/[^a-z0-9]/g, "")}.${timestamp}@example.com`;

    // Calculate a start date based on tenure
    const now = new Date();
    const monthsAgo = Math.floor(agentData.tenure * 4); // Convert tenure to roughly months
    const startDate = new Date(
      now.getFullYear(),
      now.getMonth() - monthsAgo,
      now.getDate()
    );

    // Create the agent
    const agent = await prisma.agent.create({
      data: {
        firstName,
        lastName,
        email,
        teamId: team.id,
        startDate,
        status: agentData.status,
        tenure: agentData.tenure,
        targetLeadsPerDay: Math.round(agentData.leadsPerDay),
      },
    });

    // Add metrics
    const currentMonth = 3; // March (03/10/2025)
    const currentWeek = 2; // Second week

    await prisma.metric.create({
      data: {
        agentId: agent.id,
        month: currentMonth,
        week: currentWeek,
        closeRate: agentData.closeRate / 100, // Convert from percentage
        averagePremium: agentData.avgPremium,
        placeRate: agentData.placeRate / 100, // Convert from percentage
        capScore: agentData.capScore,
        leadsPerDay: agentData.leadsPerDay,
      },
    });

    return agent;
  } catch (error) {
    console.error(`Error processing agent ${agentData.name}:`, error);
    throw error;
  }
}

async function main() {
  console.log("Starting complete agent import process...");

  try {
    // Clear existing data
    console.log("Clearing existing data...");
    await prisma.metric.deleteMany({});
    await prisma.agent.deleteMany({});
    await prisma.team.deleteMany({});

    // Process agents in sequence
    let importedCount = 0;
    let errorCount = 0;

    for (const agentData of AGENT_DATA) {
      try {
        const agent = await processAgent(agentData);
        console.log(
          `Imported: ${agent.firstName} ${agent.lastName} (${agentData.site}, ${agentData.manager})`
        );
        importedCount++;
      } catch (error) {
        console.error(`Failed to import agent ${agentData.name}`);
        errorCount++;
      }
    }

    console.log(`\nImport completed:`);
    console.log(`- Successfully imported: ${importedCount} agents`);
    console.log(`- Failed imports: ${errorCount} agents`);
    console.log(`- Total in data set: ${AGENT_DATA.length} agents`);

    // Verify import
    const finalCount = await prisma.agent.count();
    console.log(`\nTotal agents in database after import: ${finalCount}`);
  } catch (error) {
    console.error("Error during import:", error);
  } finally {
    await prisma.$disconnect();
  }
}

main().catch((e) => {
  console.error("Fatal error:", e);
  process.exit(1);
});
